env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64
  install_script:
    - pkg upgrade -y
    - pkg install -y gmake pkgconf autotools
  script:
    - ./autogen.sh
    - mkdir tmp
    - cd tmp
    - ../configure --enable-lights
    - gmake -C bld-ks-its
