language: c
dist: trusty
sudo: required
install: sudo apt-get install libusb-1.0-0-dev
script:
  - ./autogen.sh
  - mkdir tmp
  - cd tmp
  - ../configure --enable-lights
  - make base-kl
  - cd ../run/dfkfb
  - ../../tmp/bld-kl/kn10-kl dfkfb.ini
